import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><div className="flex justify-center space-x-4 mt-3">
         <Link className="text-3xl text-blue-500" href={"/"} >HOME  </Link>
         <Link className="text-3xl text-blue-500" href={"/About"} >About  </Link>
         <Link className="text-3xl text-blue-500" href={"/products"} >Product  </Link>
      </div>
        {children}
      </body>
    </html>
  );
}
